- name: install mysql
  hosts: mysql
  become: yes
  vars:
    mysql_root_pwd: ExpenseApp@1
  tasks:
  - name: installing pip
    ansible.builtin.pip:
      name: "{{ item }}"
      # state: installed 
      executable: pip3.9
    loop:
      - PyMySQL

  - name: installing mysql app
    ansible.builtin.package:
      name: mysql-server
      state: installed
      
  - name: start and enable the mysql service
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes 
  
  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_pwd }}"
      login_host: 172.31.89.97
    register: mysql_info
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "MySQL info: {{ mysql_info }}"

  - name: setup root password
    ansible.builtin.command: " mysql_secure_installation --set-root-pass {{ mysql_root_pwd }} "
    when: mysql_info.failed is true
