- name: install mysql
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql app
    ansible.builtin.package:
      name: mysql-server
      state: installed
      
  - name: start and enable the mysql service
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes 
  
  # - name: 
