- name: expence project backend server setup
  hosts: backend
  become: yes
  tasks: 
  - name: Disable Node.js module
    ansible.builtin.command:
      cmd: "dnf module disable nodejs -y"
    register: service_result1

  - name: print out put
    ansible.builtin.debug:
      msg: "{{ service_result1 }}"

  