- name: expence project backend server setup
  hosts: backend
  become: yes
  tasks: 
  - name: Disable Node.js module
    ansible.builtin.command:
      cmd: "dnf module disable nodejs -y"
    register: service_result1

  - name: print out put
    ansible.builtin.debug:
      msg: "{{ service_result1 }}"

  - name: Disable Node.js module
    ansible.builtin.command:
      cmd: "dnf module enable nodejs:20 -y"
    register: service_result2

  - name: print out put
    ansible.builtin.debug:
      msg: "{{ service_result2 }}"

  - name: install node js
    ansible.builtin.package:
      name: nodejs
      state: installed

  - name: Create a user 'expense' with a home directory
    ansible.builtin.user:
      name: expense
      create_home: yes

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: /app
      state: directory
      mode: '0755'