- name: expence project frontend server setup
  hosts: frontend
  become: yes
  tasks: 
  - name: install NGINX
    ansible.builtin.package:
      name: nginx
      state: installed
  
  - name: Enable and start the nginx service
    ansible.builtin.systemd_service:
      name: nginx
      enabled: yes
      state: started

  - name: find the the files in html directory
    ansible.builtin.find:
      patch: /usr/share/nginx/html # The directory path you want to clean
      recurse: yes  # Recurse to find files in subdirectories
      file_type: file  # Ensure it only finds files
    register: files_to_remove

  - name: Recursively remove default nginx directory
    ansible.builtin.file:
      path: "{{ item.path }}"
      state: absent  # Delete the file
    loop: "{{ files_to_remove.files }}"

  # - name: Unarchive a file that needs to be downloaded # module to download and extract an archive file (in this case, a ZIP file) from a remote source directly onto the target system.
  #   ansible.builtin.unarchive:
  #     src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
  #     dest: /usr/share/nginx/html/
  #     remote_src: yes # remote_src: yes indicates that the src file is a remote file (in this case, a URL), not a local file present on the control machi

  # - name: Copy expence.conf file from ansible to remote server 
  #   ansible.builtin.copy:
  #     src: /home/ec2-user/ansible_expense_project/expence.conf
  #     dest: /etc/nginx/default.d/expense.conf

  # - name: Restart nginx
  #   ansible.builtin.systemd_service:
  #     name: nginx
  #     state: restarted
