- name: Launch EC2 instance with a Community AMI
  connection: local
  hosts: local
  vars:
    # region: us-east-1
    img_id: ami-09c813fb71547fc4f
    instances_type: t3.micro
    security_groups_ID: sg-043967c027fdcfddb
    subnet_ID: subnet-05adc3556c09f9863
    instances:
    - mysqlserver
    - backendserver
    - frontendserver

  tasks:
  - name: installing required packages for ansible
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMySQL
    - cryptography
    - boto
    - boto3

  - name: Launch a new EC2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: "{{ instances_type }}"
      image_id: "{{ img_id }}"  # Replace with your Community AMI ID
      security_groups: "{{ security_groups_ID }}"         # Name of the security group
      subnet_id: "{{ subnet_ID }}"
    loop: "{{ instances }}"
           
      

# Install boto3 and botocore:
# Use pip to install the necessary libraries:

# sudo yum install python3-pip  # if pip3 is not installed
# sudo pip3 install boto3 botocore


# Verify Installation:

# After installation, verify that the libraries are installed correctly by running:

# python3 -c "import boto3; import botocore"


