- name: Launch EC2 instance with a Community AMI
  hosts: local
  gather_facts: no
  tasks:
    - name: Launch a new EC2 instance
      amazon.aws.ec2_instance:
        region: us-east-1
        key_name: AWSPUBKEY-DEC24  # No key pair specified
        instance_type: t3.micro
        image_id: ami-09c813fb71547fc4f  # Replace with your Community AMI ID
        security_groups: 
          - All-accessible security group          # Name of the security group
        count: 1
        wait: yes
        tags:
          Name: CommunityAMIInstance
      register: ec2_instance

    - name: Display instance information
      ansible.builtin.debug:
        var: ec2_instance


# Install boto3 and botocore:
# Use pip to install the necessary libraries:

# sudo yum install python3-pip  # if pip3 is not installed
# sudo pip3 install boto3 botocore


# Verify Installation:

# After installation, verify that the libraries are installed correctly by running:

# python3 -c "import boto3; import botocore"


